# Generated by Django 4.2.2 on 2023-07-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=200)),
                ('cat_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('isbn', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('generous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.generous')),
            ],
        ),
    ]
